@startuml

class AdcOneChannel {
	{field}-	const AdcOneChannelCfg*		const cfg
	{field}-	const uint32_t				cfgCount
	{field}-	ADC_HandleTypeDef			adc
	{field}-	ADC_ChannelConfTypeDef		channelCfg
	__Constructor__
	{method}+	AdcOneChannel	( const AdcOneChannelCfg*		const cfg,\n\t\t\t  uint32_t\t\t\t\t\tcountCfg )
	__Public methods__
	{method}+	void	irqHandler		( void )
	__Private methods__
	{method}-	void	clkEnable		( void )
	{method}-	void	clkDisable		( void )
}

package TIMER {
	
class TimCompOneChannel {
	{field}-	const timCompOneChannelCfg*	const cfg
	{field}-	TIM_HandleTypeDef			tim
	{field}-	TIM_OC_InitTypeDef			timCh
	__Constructor__
	{method}+	TimCompOneChannel	( const timCompOneChannelCfg* const cfg )
}

class TimPwmOneChannel {
	{field}-	const timPwmOneChannelCfg*		const cfg
	{field}-	TIM_HandleTypeDef				tim
	{field}-	TIM_OC_InitTypeDef				timCh
	__Constructor__
	{method}+	TimPwmOneChannel	( const timPwmOneChannelCfg* const cfg )
}

class TimInterrupt {
	{field}-	const timInterruptCfg*		const cfg
	{field}-	TIM_HandleTypeDef		tim
	__Constructor__
	{method}+	TimInterrupt	( const timInterruptCfg* const cfg )
}

}

package GPIO {

class PinMultifunc {
	{field}-	const uint32_t	cfgCount
	__Constructor__
	{method}+	PinMultifunc	( const pinCfg*	const cfg,\n\t\t\t  uint32_t		cfgCount )
}

}

@enduml
