@startuml

/' Интерфейсы периферии МК '/
package mc_interfaces {

interface PinBase {
	{abstract}{method}+	void	set		( void )
	{abstract}{method}+	void	reset		( void )
	{abstract}{method}+	void	toggle	( void )
	{abstract}{method}+	void	set		( bool	state )
	{abstract}{method}+	void	set		( int		state )
	{abstract}{method}+	void	set		( uint8_t	state )
	{abstract}{method}+	read			( void )
}

interface PinMultifuncBase {
	{abstract}{method}+	bool	reinit		( uint32_t	numberCfg )
}

interface PinMultifuncItBase {
	{abstract}{method}+	bool	checkIt	( void )
	{abstract}{method}+	void	clearIt	( void )
}

interface Port8bitBase {
	{abstract}{method}+	void		write		( uint8_t	data )
	{abstract}{method}+	void		reset		( void )
	{abstract}{method}+	void		toggle	( void )	
	{abstract}{method}+	uint8_t	read		( void )	
}

interface GlobalPortBase {
	{abstract}{method}+	BaseResult		reinitAllPorts	( void )
}

interface WdtBase {
	{abstract}{method}+	BaseResult		reinit			( uint32_t numberCfg = 0 )
	{abstract}{method}+	void			reset			( void )	
	{abstract}{method}+	void			resetService	( void )
}

interface UartBase {
	{abstract}{method}+	BaseResult		reinit				( uint32_t			numberCfg		= 0 )
	{abstract}{method}+	BaseResult		on				( void )	
	{abstract}{method}+	void			off				( void )
	{abstract}{method}+	BaseResult		tx				( const uint8_t*		const txArray,\n\t\t\t\t\t\t\t  uint16_t			length		= 1,\n\t\t\t\t\t\t\t  uint32_t			timeoutMs		= 100 )
	{abstract}{method}+	BaseResult		getByte			( uint8_t*			retrunData,\n\t\t\t\t\t\t\t  uint32_t			timeoutMs		= 100 )
	{abstract}{method}+	BaseResult		getByteWitchout		( uint8_t* 			retrunData )

}

interface TimInterruptBase {
	{abstract}{method}+	BaseResult		reinit				( uint32_t	numberCfg = 0 )
	{abstract}{method}+	BaseResult		setState			( bool	state )
	{abstract}{method}+	BaseResult		on				( void )
	{abstract}{method}+	void			off				( void )
	{abstract}{method}+	void			clearInterruptFlag	( void )
}

interface TimPwmOneChannelBase {
	{abstract}{method}+	BaseResult		reinit		( uint32_t	numberCfg = 0 )
	{abstract}{method}+	BaseResult		on		( void )
	{abstract}{method}+	void			off		( void )	
	{abstract}{method}+	void			setDuty	( float	duty )
}

interface SpiMaster8BitBase {	
	{abstract}{method}+	BaseResult		reinit			( uint32_t			numberCfg			= 0 )
	{abstract}{method}+	BaseResult		on			( void )
	{abstract}{method}+	void			off			( void )	
	{abstract}{method}+	BaseResult		tx			( const uint8_t*		const txArray,\n\t\t\t\t\t\t  uint16_t			length			= 1,\n\t\t\t\t\t\t  uint32_t			timeoutMs			= 100	)
	{abstract}{method}+	BaseResult		tx			( const uint8_t*		const txArray,\n\t\t\t\t\t\t  uint8_t*			rxArray,\n\t\t\t\t\t\t  uint16_t			length			= 1,\n\t\t\t\t\t\t  uint32_t			timeoutMs			= 100	)
	{abstract}{method}+	BaseResult		txOneItem 		( uint8_t			txByte,\n\t\t\t\t\t\t  uint16_t			count				= 1,\n\t\t\t\t\t\t  uint32_t			timeoutMs			= 100	)
	{abstract}{method}+	BaseResult		rx			( uint8_t*			rxArray,\n\t\t\t\t\t\t  uint16_t			length			= 1,\n\t\t\t\t\t\t  uint32_t			timeoutMs			= 100,\n\t\t\t\t\t\t  uint8_t			outValue			= 0xFF )
	{abstract}{method}+	BaseResult		setPrescaler	( uint32_t 			prescalerNumber	= 0	)
}

interface RccBase {
	{abstract}{method}+	RccResult	setCfg		( uint32_t	numberCfg = 0 )
	{abstract}{method}+	uint32_t	getCfgNumber	( void )	
}

interface PwrBase {
	{abstract}{method}+	BaseResult		reinit			( uint32_t numberCfg = 0 )
	{abstract}{method}+	void			pvdEnable		( void )	
	{abstract}{method}+	void			pvdDisable		( void )
}

interface AdcOneChannelBase {
	{abstract}{method}+	BaseResult		reinit						( uint32_t numberCfg = 0 )
	{abstract}{method}+	BaseResult		startContinuousConversion		( void )
	{abstract}{method}+	void			stopContinuousConversion		( void )
	{abstract}{method}+	uint32_t		getMeasurement				( void )
}

}

/' Реализация интерфейсов периферии МК '/
package "Mc interfaces implementation  " {

class AdcOneChannel {
	{field}-	const AdcOneChannelCfg*		const cfg
	{field}-	const uint32_t				countCfg
	{field}-	ADC_HandleTypeDef			adc
	{field}-	ADC_ChannelConfTypeDef		channelCfg
	__Constructor__
	{method}+AdcOneChannel	( const AdcOneChannelCfg*		const cfg,\n\t\t\t  uint32_t\t\t\t\t\tcountCfg )
	__Public methods__
	{method}+	void	irqHandler		( void )
	__Private methods__
	{method}-	void	clkEnable		( void )
	{method}-	void	clkDisable		( void )
}

AdcOneChannelBase <|-- AdcOneChannel

}
/'
interface {
	{abstract}{method}+	
}
'/


@enduml